
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/redraskal/r6-dissect/dissect"


)

var tests = []testing.InternalTest{

	{"TestSelectBlenderCameraTrackDefaultsToRecordingPlayer", _test.TestSelectBlenderCameraTrackDefaultsToRecordingPlayer},

	{"TestSelectBlenderCameraTrackMatchesSelectors", _test.TestSelectBlenderCameraTrackMatchesSelectors},

	{"TestBlenderCameraEulerUsesWrappedDegrees", _test.TestBlenderCameraEulerUsesWrappedDegrees},

	{"TestBlenderCameraEulerPrefersViewingHeadingForYaw", _test.TestBlenderCameraEulerPrefersViewingHeadingForYaw},

	{"TestBlenderCameraEulerSupportsLevelCameraOffsets", _test.TestBlenderCameraEulerSupportsLevelCameraOffsets},

	{"TestBlenderCameraEulerPrefersRecoveredPitchWhenAvailable", _test.TestBlenderCameraEulerPrefersRecoveredPitchWhenAvailable},

	{"TestChooseBlenderCameraOutputPrefersDenserUsernameTrack", _test.TestChooseBlenderCameraOutputPrefersDenserUsernameTrack},

	{"TestChooseBlenderCameraOutputPrefersResolvedRecordingPlayerTrack", _test.TestChooseBlenderCameraOutputPrefersResolvedRecordingPlayerTrack},

	{"TestBlenderShouldScanCandidatePropsOnlyForRecordingPlayerOrExplicitUsername", _test.TestBlenderShouldScanCandidatePropsOnlyForRecordingPlayerOrExplicitUsername},

	{"TestBlenderCameraTrackScorePenalizesOriginLikeTrack", _test.TestBlenderCameraTrackScorePenalizesOriginLikeTrack},

	{"TestRenderBlenderCameraScriptIncludesMetadataAndKeyframes", _test.TestRenderBlenderCameraScriptIncludesMetadataAndKeyframes},

	{"TestBlenderStableViewingHeadingContinuousClampsWildPrefix", _test.TestBlenderStableViewingHeadingContinuousClampsWildPrefix},

	{"TestBlenderBaselinePitchRollUsesStableSample", _test.TestBlenderBaselinePitchRollUsesStableSample},

	{"TestReadDefuserTimerIgnoresCompleteWithoutKnownPlayer", _test.TestReadDefuserTimerIgnoresCompleteWithoutKnownPlayer},

	{"TestHeaderRecordingPlayerFallsBackToProfileID", _test.TestHeaderRecordingPlayerFallsBackToProfileID},

	{"TestMovementDirectionRegression360PatternReplay", _test.TestMovementDirectionRegression360PatternReplay},

	{"TestMovementApplyDerivedViewingDirectionsPrefersProjectedTimeline", _test.TestMovementApplyDerivedViewingDirectionsPrefersProjectedTimeline},

	{"TestMovementApplyDerivedViewingDirectionsUsesDerivedForGapsOnly", _test.TestMovementApplyDerivedViewingDirectionsUsesDerivedForGapsOnly},

	{"TestMovementDataMergesPositionAndRotation", _test.TestMovementDataMergesPositionAndRotation},

	{"TestMovementRecordAtUsesStableZeroActorPrefix", _test.TestMovementRecordAtUsesStableZeroActorPrefix},

	{"TestMovementRecordAtKeepsZeroActorWithoutStablePrefix", _test.TestMovementRecordAtKeepsZeroActorWithoutStablePrefix},

	{"TestMovementDataPrimaryTracks", _test.TestMovementDataPrimaryTracks},

	{"TestMovementDataPrimaryTrackGrouping", _test.TestMovementDataPrimaryTrackGrouping},

	{"TestGuessMovementTrackPlayers", _test.TestGuessMovementTrackPlayers},

	{"TestMovementDataDiscoversNonDefaultPropIDs", _test.TestMovementDataDiscoversNonDefaultPropIDs},

	{"TestMovementDataIncludesUsagePercentages", _test.TestMovementDataIncludesUsagePercentages},

	{"TestMovementDataOptionsRespectsPropOverrides", _test.TestMovementDataOptionsRespectsPropOverrides},

	{"TestRadiansToWrappedDegrees", _test.TestRadiansToWrappedDegrees},

	{"TestMovementDataIgnoresNearZeroPropIDs", _test.TestMovementDataIgnoresNearZeroPropIDs},

	{"TestMergeSoloRotationTracks", _test.TestMergeSoloRotationTracks},

	{"TestMovementDataY11SinglePropCarriesPositionAndRotation", _test.TestMovementDataY11SinglePropCarriesPositionAndRotation},

	{"TestMovementY11CandidatePositionFallsBackToSecondary", _test.TestMovementY11CandidatePositionFallsBackToSecondary},

	{"TestMovementRecordAtWithPropsY11DoesNotTreatRotationPacketsAsPositionWhenPropsDiffer", _test.TestMovementRecordAtWithPropsY11DoesNotTreatRotationPacketsAsPositionWhenPropsDiffer},

	{"TestMovementY11CandidateQuaternionFallsBackToImplicitSecondaryXYZ", _test.TestMovementY11CandidateQuaternionFallsBackToImplicitSecondaryXYZ},

	{"TestMovementNormalizedPackedQuaternion", _test.TestMovementNormalizedPackedQuaternion},

	{"TestMovementTrackQualityPositionScorePrefersDensePositionStream", _test.TestMovementTrackQualityPositionScorePrefersDensePositionStream},

	{"TestMovementY11RankRotationChoicesUsesBestPositionPairing", _test.TestMovementY11RankRotationChoicesUsesBestPositionPairing},

	{"TestMovementDirectionTargetVectorStreamsDeriveHeadingFromPlayerPosition", _test.TestMovementDirectionTargetVectorStreamsDeriveHeadingFromPlayerPosition},

	{"TestMovementDirectionFinalizeSoloScalarStreamsFusesBeforeIntegrating", _test.TestMovementDirectionFinalizeSoloScalarStreamsFusesBeforeIntegrating},

	{"TestMovementDirectionPropFusedDeltaStreamsMergeAcrossActors", _test.TestMovementDirectionPropFusedDeltaStreamsMergeAcrossActors},

	{"TestMovementTrackEffectivePositionSamplesPenalizesStaticAnchors", _test.TestMovementTrackEffectivePositionSamplesPenalizesStaticAnchors},

	{"TestMovementTrackLooksOriginLike", _test.TestMovementTrackLooksOriginLike},

	{"TestMovementBestSameActorDirectionCandidatePrefersMatchingActor", _test.TestMovementBestSameActorDirectionCandidatePrefersMatchingActor},

	{"TestMovementDirectionFloat64StreamsFindSoloScalarCandidates", _test.TestMovementDirectionFloat64StreamsFindSoloScalarCandidates},

	{"TestMovementDirectionFloat32PairStreamsFindSoloPairCandidates", _test.TestMovementDirectionFloat32PairStreamsFindSoloPairCandidates},

	{"TestMovementDirectionTargetedAlignedWordDeltaStreamsFindsInt32Lane", _test.TestMovementDirectionTargetedAlignedWordDeltaStreamsFindsInt32Lane},

	{"TestMovementDirectionPropProbeForPropGroupsLaneActors", _test.TestMovementDirectionPropProbeForPropGroupsLaneActors},

	{"TestMovementBestDenseFallbackDirectionCandidatePrefersCoverage", _test.TestMovementBestDenseFallbackDirectionCandidatePrefersCoverage},

	{"TestMovementBestDenseLocalFragmentDirectionCandidateStitchesRawFragments", _test.TestMovementBestDenseLocalFragmentDirectionCandidateStitchesRawFragments},

	{"TestMovementDirectionProjectCandidateTimelineProjectsBeyondMovementSamples", _test.TestMovementDirectionProjectCandidateTimelineProjectsBeyondMovementSamples},

	{"TestMovementDirectionAnchorMinPredictionsAllowsShortDenseFragments", _test.TestMovementDirectionAnchorMinPredictionsAllowsShortDenseFragments},

	{"TestMovementBestMotionHeadingFallbackBuildsFullCoverageTrack", _test.TestMovementBestMotionHeadingFallbackBuildsFullCoverageTrack},

	{"TestMovementDirectionFloat64PairStreamsFindSoloPairCandidates", _test.TestMovementDirectionFloat64PairStreamsFindSoloPairCandidates},

	{"TestMovementDirectionDeltaIntegratedSamplesUnwrapsTurns", _test.TestMovementDirectionDeltaIntegratedSamplesUnwrapsTurns},

	{"TestMovementDirectionAnchorStreamShortlistKeepsDensePropAndActor", _test.TestMovementDirectionAnchorStreamShortlistKeepsDensePropAndActor},

	{"TestMovementFuseActorSplitDirectionStreamsStitchesIntegratedFragments", _test.TestMovementFuseActorSplitDirectionStreamsStitchesIntegratedFragments},

	{"TestMovementRecoveredClockEntriesTrimTrailingNonPositive", _test.TestMovementRecoveredClockEntriesTrimTrailingNonPositive},

	{"TestMovementDataY11AttachesRecoveredTailClock", _test.TestMovementDataY11AttachesRecoveredTailClock},

	{"TestMovementRotationHeadingHybridModelHandlesMixedSoloPackets", _test.TestMovementRotationHeadingHybridModelHandlesMixedSoloPackets},

	{"TestMovementApplyDerivedViewingDirectionsKeepsGoodDerivedTimeline", _test.TestMovementApplyDerivedViewingDirectionsKeepsGoodDerivedTimeline},

	{"TestMovementFoldPitchDegrees", _test.TestMovementFoldPitchDegrees},

	{"TestMovementGuessViewPitchAxisPrefersResponsiveAxis", _test.TestMovementGuessViewPitchAxisPrefersResponsiveAxis},

	{"TestMovementDirectionProjectedPitchTimelineScorePrefersPitchLikeSignal", _test.TestMovementDirectionProjectedPitchTimelineScorePrefersPitchLikeSignal},

	{"TestMovementDirectionPitchAlignmentsForStreamIncludesTimedFallbacks", _test.TestMovementDirectionPitchAlignmentsForStreamIncludesTimedFallbacks},

	{"TestWinningTeamFromScoreDelta", _test.TestWinningTeamFromScoreDelta},

	{"TestRoundEndY9S4DoesNotFlipWinnerOnPlantFromLosingTeam", _test.TestRoundEndY9S4DoesNotFlipWinnerOnPlantFromLosingTeam},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "github.com/redraskal/r6-dissect/dissect"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

